### ISSUE TITLE
เซ็ตระบบทำงานเบื้องต้น

### ISSUE THREAD

**Issue by NattapasJenphet** [NattapasJenphet/Kiragames_Intern#1]
set account

- [x] nattpas@kiragames.com

- [x] Github : @nattapasjenphet >>> smartGit

**Comment by ghost** [comment]
ติดตั้งเครื่องมือ
* Slack
* Hangout
* SmartGit

สมัคร account
* Slack
* Github
* Facebook Group
* Calendar
