### ISSUE TITLE
ทำ model และ texture ถนนใช้จริงในเกม 1 prefab

### ISSUE THREAD

**Issue by ghost** [NattapasJenphet/Kiragames_Intern#10]
* ออกแบบองค์ประกอบของถนนทั้งหมดก่อนว่าทั้งสายจะมีอะไรบ้าง ให้ระวังข้างทางเป็นพื้นที่วาง พื้นที่วางในที่นี้ไม่ใช้ติดรั่ว
* กำหนดความยาวของถนนแต่ละ prefab ตอนนี้ใช้ขนาดเท่ากันไปก่อน
* ขึ้นทำ model เป็นตัวๆ ใส่ไว้ใน folder นอกโปรเจก
* Texture สามารถใช้ของคนอื่นก่อนได้
* นำ model และ texture มาสร้างเป็น prefab เพื่อใช้จริงในเกม 1 prefab
* แก้ไข prefab เดิมให้รถวิ่งได้เบื้องต้นก่อน
* กำหนดระยะเวลาทำงาน อาจจะแบ่งงานเป็นส่วนก็ได้

**Comment by NattapasJenphet** [comment]
- รถยนต์
  - [x] โมเดล
  - [ ] texture
- องค์ประกอบของถนน
   - เสาไฟ 
  - [x] โมเดล
  - [x] texture
   - รั่ว
  - [x] โมเดล
  - [x] texture
   - ต้นไม้
  - [x] โมเดล
  - [x] texture
   - ตึก
  - [x] โมเดล
  - [x] texture

**Comment by ghost** [comment]
ใน issue ไม่ได้บอกว่าให้ทำรถครับ บอกแค่ถนน

**Comment by ghost** [comment]
* ยังขาด คือต้องเอางานที่เราทำใส่ไว้ใน git เพื่อให้คนอื่นทำต่อได้
> ขึ้นทำ  model เป็นตัวๆ ใส่ไว้ใน folder นอกโปรเจก
* ผมหา model ต้นไม้ไม่เจอ ตอนนี้อยู่ตรงไหนครับ
* ขนาดของตึกดูเล็กไปครับ เหมือนสัดส่วนจะไม่ตรงกับความเป็นจริง

**Comment by NattapasJenphet** [comment]
- สร้างโฟลเดอร์ใส่ไฟล์โมเดลแยกไว้แล้วครับ
- ย้ายโมเดลต้นไม้มาใส่ในโฟลเดอร์ที่ถูกต้องละครับ
