### ISSUE TITLE
ออกหน้าจอเกม Tic-Tac-Toe (OX)

### ISSUE THREAD

**Issue by ghost** [NattapasJenphet/Kiragames_Intern#13]
ออกแบบหน้าจอของเกม Tic-Tac-Toe หรือ OX
เป็นการแข่งระหว่าง 2 คน ไม่มี Com
โครงสร้างจะมี 2 scene คือ Menu, Game
* Menu ใช้โครงสร้างจาก issue #12
* Game ใช้ Tutorials https://unity3d.com/learn/tutorials/tic-tac-toe/introduction-and-setting-project?playlist=17111

ตัวเกมจะไม่มีรายละเอียดมากจะเน้นการวาง layout, animation, และตัวเกมเล่นจนจบได้

**Layout**
เกมจะออกแบบเพื่อครื่อง android จอแนวตั้งทุกขนาด
ให้ทำ screenshot ของทั้ง 2 scene มาดูก่อน
โดยเน้นว่าจะมีอะไรบ้างบนหน้าจอ
มีรายละเอียดที่ยังไม่ได้ใช้งานด้วยเช่น ปุ่มต่างๆ ใน menu ที่อาจจะอยู่ในเกมนี้ได้

**Animation**
หลังจากได้ screenshot ก็มาออกแบบ animation
animation จะเป็นแสดงรอบเดียวจบ แต่ก็ยังแสดงทั้งตอนเข้า scene และออก scene ในหน้า menu
ส่วนในหน้า game ยังไม่ได้มี

**Comment by NattapasJenphet** [comment]
หน้า menu
- กด tap ที่หน้าจอเพื่อเริ่มเกม
- แทบแสดงสถานะเงินในปัจจุบัน
- แทบแสดงสถานะของโทรศัพท์ (มุมบนซ้าย)
![image](https://user-images.githubusercontent.com/33273784/34199520-a18abd24-e5a0-11e7-9cbb-bcb9655525e5.png)
หน้า Game
- มี score บอกคะแนน
- มีคำที่ใช้เป็นสัญลักษณ์บอกเมื่อ turn ของผู้เล่น
- ปุ่ม replay สำหรับกดเริ่มเกมใหม่เมื่อจบเกม
- ปุ่ม back สำหรับกดกลับ
- ปุ่มร้านค้าสำหรับซื้อ skin 
![image](https://user-images.githubusercontent.com/33273784/34199704-3dd144e6-e5a1-11e7-8bc9-ca36b9ab3a14.png)

**Comment by ghost** [comment]
**Menu**
* จำนวนเงินและสถานะโทรศัพท์ ตัดออกไป
* ตรงแถวปุ่มให้มี 3 ปุ่มแรก ของ issue #12 คือ skin, options, game center

**Game**
* จำนวนเงิน ตัดออกไป
* ปุ่ม Replay เป็น Reset

ขอทำ screenshot ตามที่บอกมาอีกรอบครับ

**Comment by NattapasJenphet** [comment]
Menu
![image](https://user-images.githubusercontent.com/33273784/34201439-12d3aee0-e5a7-11e7-97e8-3f0fa803ba48.png)

Game
![image](https://user-images.githubusercontent.com/33273784/34201315-b1c86906-e5a6-11e7-94c0-ebcc5507c3f9.png)

**Comment by ghost** [comment]
สร้างโปรแจดใหม่ชื่อ TicTacToe วาง layout ตาม screenshot และให้ tap to play ในหน้า menu และ < ในหน้า game ใช้งานได้ commit พวกนี้มากก่อนแล้ว ออกแบบ animation ต่อ โดยทำให้หน้า menu ก่อน

**Comment by NattapasJenphet** [comment]
ออกแบบ animation หน้า menu
![page 1](https://user-images.githubusercontent.com/33273784/34250878-ccfffcc8-e670-11e7-9b03-33db11a0774b.jpg)
![page 2](https://user-images.githubusercontent.com/33273784/34250879-cd2f41a4-e670-11e7-8dc2-3acace048741.jpg)

**Comment by ghost** [comment]
ขาด
* tap to play ในหน้า menu และ < ในหน้า game ใช้งานได้

**Comment by ghost** [comment]
Animation
หลังจากได้ screenshot ก็มาออกแบบ animation
animation จะเป็นแสดงรอบเดียวจบ แต่ก็ยังแสดงทั้งตอนเข้า scene และออก scene ในหน้า menu
ส่วนในหน้า game ยังไม่ได้มี

ยังขาดตอน "ออก scene ในหน้า menu"

**Comment by NattapasJenphet** [comment]
Animation แสดงสำหรับออก scene ในหน้า menu เป็นยังไงหรอครับ

**Comment by ghost** [comment]
ตอนนี้เจมทำตอนเข้า scene ไปแล้ว

**Comment by ghost** [comment]
กด tap แล้วเล่น animation ย้อนกลับก็ได้

**Comment by NattapasJenphet** [comment]
ผมทำเป็น animation loadscene แทนได้มั้ยครับ

**Comment by ghost** [comment]
ขอปรับ animation ตอนเข้า scene ให้ใช้เวลาให้สั้นลง ตอนนี้ใช้เวลาเยอะไปหน่อยกว่าจะจบ
