### ISSUE TITLE
สร้างวิวและถนนเพื่อกำหนดมุมมองของเกม

### ISSUE THREAD

**Issue by ghost** [NattapasJenphet/Kiragames_Intern#4]
* องค์ประกอบของวิวเบื้องต้น
    * ท้องฟ้า
    * วิวข้างทาง ตึก ต้นไม้
    * ถนน
* ทำเป็นท่อนแล้วทำเป็น prefab
* ทำ script วางถนนจาก prefab ต่อๆกัน
* ทดสอบให้เคลื่อนที่ไปข้างหน้าง่ายๆ

**Comment by NattapasJenphet** [comment]
- [x] ท้องฟ้า
- [x] วิวข้างทาง ตึก ต้นไม้
- [x] ถนน
- [x] ทำเป็นท่อนแล้วทำเป็น prefab
- [x] ทำ script วางถนนจาก prefab ต่อๆกัน  
> ติดตรง Instantiate
- [x] ทดสอบให้เคลื่อนที่ไปข้างหน้าง่ายๆ

**Comment by dum999** [comment]
เจมออกแบบให้ถนนมี 5 ชิ้น วางเรียงต่อกันตามลำดับ
### ปัญหา
* ถนนไม่ถูกว่าเรียงตามลำดับ
### คำแนะนำ
* ลดการ hardcode โดยอาจใช้ตัวแปรและการคำนวนมาช่วย
* ลดโคดที่ซำ้กันลงโดยอาจร่วมเป็น function หรือคิดวิธีโคดใหม่
* ปรับปรุงการใช้ตัวแปร create[]
* ลองคิดการหาตำแหน่งของรถว่าอยู่บนถนนชิ้นไหนด้วย z / 30

**Comment by ghost** [comment]
เจมออกแบบให้ถนนมี 5 ชิ้น วางเรียงต่อกันตามลำดับ
### ปัญหา
* ถนนไม่ถูกว่าเรียงตามลำดับ
### คำแนะนำ
* การให้ค่าเริ่มต้นตัวแปรของ Car และ Distance ควรเลือกใช้วิธีเดียวจากโคดหรือ editor ถ้าจะใช้ทั้ง 2 ต้องเพิ่มโคดเช็ค null
* ลดการ hardcode โดยอาจใช้ตัวแปรและการคำนวนมาช่วย
* ลดโคดที่ซำ้กันลงโดยอาจร่วมเป็น function หรือคิดวิธีโคดใหม่
* ปรับปรุงการใช้ตัวแปร create[]
* ลองคิดการหาตำแหน่งของรถว่าอยู่บนถนนชิ้นไหนด้วย z / 30

**Comment by ghost** [comment]
### ปัญหา
* รถวิ่งไปแล้วกระโดด
* ถนนไม่หายไป
### คำแนะนำ
* มี resource ท้องฟ้าที่ไม่ใช้ ควรเก็บไว้นอกโปรเจก อาจสร้าง folder ไว้นอก Car Hello World
