### ISSUE TITLE
การเคลื่อนที่ของรถ

### ISSUE THREAD

**Issue by ghost** [NattapasJenphet/Kiragames_Intern#5]
* การเร่งและเบรค เพื่อวิ่งไปบนถนน
* การเลี้ยวโดยใช้ Accelerometer
* คิดเงื่อนไขเมื่อรถออกนอกถนน เบื้องต้นที่ต้องเลือก
    1. ชนรั่วทำให้รถยังอยู่บนถนน
        * หักแต้ม
        * ไม่มีผลอะไรขับต่อไป
    1. ตกถนน
        * เริ่มใหม่
        * ขับต่อจากจุดนั้น
        * จบเกม

**Comment by ghost** [comment]
อธิบายการออกแบบ
* การเร่งและเบรค เพื่อวิ่งไปบนถนน
* การเลี้ยวโดยใช้ Accelerometer

**Comment by NattapasJenphet** [comment]
- การเร่งและการเบรค
    - ปุ่มเร่งอยู่ทางด้านขวา (ในเกมปกติจะ auto accelerator ให้แต่ความเร็วจะช้ากว่าการกดปุ่มเร่ง)
       เพิ่มความเร็วให้รถเคลื่ยนที่ไปข้างหน้า 
       มีลิมิตของการเร่งความเร็ว 
    - ปุ่มเบรคอยู่ทางด้านซ้าย
       ลดความเร็วของรถ
       มีลิมิตของการลดความเร็ว = 0
- การเลี้ยวโดย Accelerometer ความเร็วการเลี้ยวทั้งซ้ายและขวาเท่ากัน
   มีการกำหนดความเร็วขั้นต่ำที่จะสามารถเลี้ยวได้

**Comment by ghost** [comment]
เพิ่มรายละเอียดกว่านี้ครับ ผมเห็นทำไว้เยอะกว่านี้ เอาแค่ 2 ข้อแรกครับ

**Comment by ghost** [comment]
### ปัญหา
* กดเร่งไปถึงความเร็วที่ 800 สักพักรถจะหยุด แต่ความเร็วก็ยังคง 800 พอปล่อยคันเร่งความเร็วจะลดเหลือ 0 กดเร่งใหม่ความเร็วขึ้นไปถึง 800 รถไม่มีการขยับเลย
* การเบรกไม่ต่างจากการปล่อยคันเร่ง คือหลังจากปล่อยคันเร่ง ไม่ว่าจะกดเบรกหรือไม่ ช่วงเวลารถลดความเร็วจนเหลือ 0 พอๆกัน

**Comment by ghost** [comment]
### แนะนำ
* แก้ปัญหาชนขอบถนนแล้วรถหยุด
![screen shot 2560-11-10 at 17 58 33](https://user-images.githubusercontent.com/25471076/32655596-d1dad1d2-c640-11e7-8936-b806c37741f2.png)

**Comment by ghost** [comment]
### คำแนะนำ
* ยืดเวลาถึง Top Speed ออกไป ดูจากเกมอื่นว่าใช้เวลากี่วินาที
* การเร่ง ช่วงความเร็วต้นจะมีอัตราเร่งมาก ช่วงความเร็วปายจะมีอัตราเร่งลดลง
* การเบรคตอนนี้ยังทดสอบได้ไม่มากเพราะการเร่งถึง Top speed ใช้เวลาเร็วมาก แต่คิดว่าควรคำนึงเรื่องการเบรคเพื่อหลบสิ่งกรีดขวาง
* การเลี้ยวทำให้เกิดการกระตุก

**Comment by ghost** [comment]
### คำแนะนำ
https://unity3d.com/learn/tutorials/modules/beginner/live-training-archive/hover-car-physics?playlist=17120
* อาจจะไม่ตรงเพราะเราไม่ได้ใช้ความสูง ต้องมาปรับใช้
* มีทำเสียงในนั้นด้วยแต่ยังไม่ต้องทำเดี๋ยวสร้างเป็น issue อีกตัว

**Comment by ghost** [comment]
ปัญหาการทดสอบ ให้แก้ไขแบบง่ายๆ เพื่อการทดสอบที่ง่ายขึ้น
* วิ่งไปชนกล่องแล้วทำอะไรต่อไม่ได้
หมายเหตุ: สามารถทำเครื่องมือขึ้นมาเองได้เลย เพื่อใช้ทดสอบเอง การทดสอบเป็นงานหลักของผู้พัฒนา
