### ISSUE TITLE
ปรับอัตราส่วนให้เหมือนโลกจริง

### ISSUE THREAD

**Issue by ghost** [NattapasJenphet/Kiragames_Intern#6]
* ค้นหาข้อมูลขนาดของวัตถุจริงที่ใช้ในเกมเบื้องต้น  ในหน่วยเมตร(กว้างxยาวxสูง) ได้แก่
    * รถ ตัวอย่าง 2x4x1.5
    * ถนน 1 เลน
    * รั่ว
    * ต้นไม้
    * ตึก
* ใส่รั่วให้กับถนน
* ทำถนนเป็น 4 เลน
* ปรับขนาดวัตถุเบื้องต้นในเกม โดยลองใช้อัตราส่วน unity3d 1 หน่วย เท่ากับ 1 เมตร
* ปรับมุมมองเพื่องานจริง
    * หาขนาด prefab ของถนน ที่ไม่ให้เกิดที่ว่างข้างทาง
    * กำหนดระยะไกลสุดของถนนที่ต้องใช้ script วาง
    * ทดสอบเล่นและปรับมุมมองให้ได้มุมสนุกที่สุดสำหรับเกม

**Comment by NattapasJenphet** [comment]
- รถ 1.8 x 1.4 x 4.7 m
![image](https://user-images.githubusercontent.com/33273784/32873698-14b2e9f8-cac0-11e7-94fe-f80ede753edc.png)
 - ถนน
    - ถนน 1 เลนกว้าง 3 m
![image](https://user-images.githubusercontent.com/33273784/32873907-564bf3b8-cac1-11e7-90da-c0369f2ad43f.png)
 - รั่ว สูง 1 m
 - ต้นไม้ สูง 4 m
 - ตึก สูง 3-5+ m
 - ปรับมุมมองเพื่องานจริง
    - ขนาด prefab ถนน scale ความกว้าง 3 m
    - ระยะไกลสูง 140 m (ถนนยาว 150 [30x5] m)
 - มุมกล้อง ตัวอย่าง
    - need for speed no limit
![image](https://user-images.githubusercontent.com/33273784/32881099-99271714-cae2-11e7-9961-24a91b138faa.png)
    - NASCAR Heat Mobile
![image](https://user-images.githubusercontent.com/33273784/32881171-e80baf2a-cae2-11e7-9e1c-0650cad5fed0.png)
