### ISSUE TITLE
แสดงค่าความเร็วบนหน้าจอ

### ISSUE THREAD

**Issue by ghost** [NattapasJenphet/Kiragames_Intern#7]
แสดงความเร็วในหน่วย km/hr จากของเดิมเจมใช้ค่าตัวแปร speed ซึ่งดูแล้วไม่ใช่ความเร็วจริงๆของรถ
ความเร็วจริงๆน่าจะเป็นค่า velocity.z มากกว่า
ให้หาข้อมูลที่อ้างอิงความเร็วจากตัวรถแล้วแปลงมาเป็นความเร็วที่แสดง
ซึ่งการกำหนดอัตรส่วน 1:1 เมตรไว้
ส่วนการบังคับเร่งยังไม่ได้ต้องปรับ แสดงความเร็วมากน้อยปล่อยไปก่อน

**Comment by NattapasJenphet** [comment]
https://answers.unity.com/questions/421649/how-to-get-car-speed-.html
https://answers.unity.com/questions/15414/how-can-i-make-an-on-screen-speedometer.html

**Comment by NattapasJenphet** [comment]
- m/s --> km/h * 3.6 
![image](https://user-images.githubusercontent.com/33273784/32933092-0990a4ac-cb9c-11e7-8991-06a59119d032.png)
- ปัญหาตัวเลขไม่นิ่ง
   การควบคุม : ปล่อยให้รถเคลื่อนไปเอง
   ตัวเลขไม่นิ่ง ตัวเลขแกว่งขึ้นลงอยู่ที่ 3 ค่า
![image](https://user-images.githubusercontent.com/33273784/32933649-12cf2538-cb9d-11e7-9be2-93646b9878f4.png)
![image](https://user-images.githubusercontent.com/33273784/32933430-bb0defaa-cb9c-11e7-9163-f2d171a29cc7.png)
![image](https://user-images.githubusercontent.com/33273784/32933569-f34760e0-cb9c-11e7-81f1-bfc29c571aca.png)

**Comment by ghost** [comment]
* ข้อ 1
    * m/s คือค่าอะไร
    * สูตรที่ให้มาหมายความว่าอะไร ทำไมเราถึงใช้สูตรนี้
* ข้อ 2
    * ตัวเลขไม่นิ่งเกิดจากสูตรที่ว่ารึป่าว ถ้าใช่ต้องพิจารณาสูตร

แนะนำ
* หาตัวแปรของตัวรถว่าเราควรใช้ค่าไหน ค่า velocity.z เป็นเพียงสมมุติฐานของผม
* อาจจะใช้วิธีเก็บค่าตำแหน่ง z ที่ผ่านมาเปลียนเทียบระยะทางที่ได้ตามเวลา
* หาข้อมูลมากกว่านี้

**Comment by NattapasJenphet** [comment]
ใน unity3d แทนค่า 1 unit = 1 เมตร 
ใช้สูตร velocity.magnitude จะได้ค่า m/s
แล้วนำไปหาค่า km/hr เท่ากับ km/3600 วินาที (60 นาที x 60 วินาที)

**Comment by ghost** [comment]
commit ที่ผ่านมา เจมเอา `#8` มาร่วม commit ไปด้วย
ถ้ามีงานใน issue อื่นต้องใส่เบอร์ใน commit message ด้วย ตัวอย่าง `#7 แสดงความเร็วเป็น km/hr #8 เพิ่มเสียงรถ`

ผมไล่จากโคดเจมใช้ velocity.z ในการคำนวน ผมสงสัยบรรทัดนี้เราไม่ต้องคำนวนก็ได้รึป่าว

    float sqarMagZ = Mathf.Sqrt(GetComponent<Rigidbody>().velocity.z * GetComponent<Rigidbody>().velocity.z);

ผมทดสอบดูแล้วค่าของ velocity.z ก็ยังไม่ใช่ความเร็วรถจริงๆ ครับ
ผมทดสอบโดนให้มันหยุดอยู่เฉยๆ ความเร็วก็ยังมีอยู่ซึ่งมันควรจะเป็น 0
ต้องหาวิธีหาความเร็วแบบอื่นดูครับ

**Comment by NattapasJenphet** [comment]
ครั้งต่อไปจะใส่ commit ให้ครบครับ

ตามสูตรที่หาข้อมูลมาคือ The length of the vector is **_square root of (x.x+y.y+z.z)._**

สูตรนี้ประยุกต์มาจากสูตรของบน แต่ผมตัดเอาความเร็วในแกน x กับแกน y ออก เลยทำให้ในสูตรเหลือแต่ velocity.z 
`float sqarMagZ = Mathf.Sqrt(GetComponent<Rigidbody>().velocity.z * GetComponent<Rigidbody
().velocity.z);`

ผมได้กำหนดความเร็วขั้นต่ำเอาไว้ เพราะฉะนั้นค่า velocity.z จะไม่เป็น 0 ครับ

**Comment by ghost** [comment]
* ลองดูนะครับ sqarMagZ มันได้ผลลัพท์เท่ากับ GetComponent<Rigidbody>().velocity.z รึป่าว ค่อยๆคิดครับ
* หาวิธีใหม่ครับ velocity.z ไม่ใช่ความเร็วจริงของรถ

**Comment by ghost** [comment]
* ค่าที่แสดงใน Fix Speed ไม่ถูกต้อง ค่าควรจะเท่ากับ velocity
* ดูจากสูตรการเก็บค่า ยังไม่เข้าใจการใช้งาน Update และ FixUpdate
* สูตรต้องเป็น (current position - last position) / time * 3.6

**Comment by ghost** [comment]
แก้ใขให้แล้วครับ
