### ISSUE TITLE
กำหนดค่าเกี่ยวกับความเร็วและเพิ่มเสียงเครื่องยนต์รถ

### ISSUE THREAD

**Issue by ghost** [NattapasJenphet/Kiragames_Intern#8]
* เสียงเครื่องยนต์ตามการเร่งและเบรค
* มีการเปลียนเกียร์ โดยให้กำหนดจำนวนเกียร์ได้ 4-6 เกียร์
* ปรับปรุงการเร่งให้สามารถกำหนด top speed ได้เป็น km/hr
* กำหนดเวลาความเร็วจาก 0 - top speed ได้เป็นวินาที

**Comment by NattapasJenphet** [comment]
- [ ] เสียงเครื่องยนต์ตามการเร่งและเบรค
- [x] มีการเปลียนเกียร์ โดยให้กำหนดจำนวนเกียร์ได้ 4-6 เกียร์
> เกียร์ตอนนี้มี 4 เกียร์
- [x] ปรับปรุงการเร่งให้สามารถกำหนด top speed ได้เป็น km/hr
- [x] กำหนดเวลาความเร็วจาก 0 - top speed ได้เป็นวินาที
> top speed = 216 km/hr 
> จาก 0 - top speed ใช้เวลาประมาณ 1.50 นาที

**Comment by NattapasJenphet** [comment]
- **ปัญหา**
  เสียงดีเลย์

**Comment by ghost** [comment]
ยังไม่ assign ยังไม่ต้องทำครับ

**Comment by ghost** [comment]
ให้ออกแบบแต่ละข้อ และนำมาอธิบายว่าจะโคดอย่างไร
ใน issue ก่อนนำไปทำจริง

**Comment by NattapasJenphet** [comment]
- เสียงเครื่องยนต์ตามการเร่งและเบรค 
   - มีเสียงเร่งเครื่องยนต์จะทำงานเมื่อกดปุ่มเร่งความเร็ว
   - มีเสียงเบรคจะทำงานเมื่อกดปุ่มเบรค
สร้าง audio source 2 ตัวมาเก็บเสียง เร่ง และ เบรค ให้สามมารถทำงานแยกกันได้
- มีการเปลี่ยนเกียร์ โดยให้กำหนดจำนวนเกียร์ได้ 4-6 เกียร์
   - โค้ดที่เขียนนั้นกำหนดไว้ 4 เกียร์ โดยจะตัดเสียงตอนเร่งความเร็วรถ แบ่งออกเป็น 4 ส่วน เรียกใช้งานเสียงตามความเร็วของรถ สร้างตัวแปรในเก็บสถานะเกียร์ของรถเพื่อเรียกใช้งาน

**Comment by ghost** [comment]
ผมช่วยออกแบบให้นะครับ
* ความเร็วของรถจะแปรผันตามเกียร์และรอบเครื่องยนต์ ฉนั้นความเร็วของรถจะคล้ายกับกราฟโพรเจกไทล์ด้านเดียว
* แทนกราฟโพรเจกไทล์ แกน y = ความเร็วสูงสด x = เวลาจาก 0 ถึงความเร็วสูงสุด
* สร้างตัวแปรมา 1 ตัวเก็บจำนวนเกียร์ และใช้จำนวนตัวแปรไปแบ่งความเร็วตามจำนวนเกียร์
* แบ่งความเร็วเป็นส่วนตามจำนวนเกียร์ ความห่างของความเร็วเท่าๆกันก่อน แล้วปรับจูนใน issue ต่อไป
* เสียงของเครื่องยนต์ จะแปรผันตามเกียร์ คือความเร็วสูงสุดของเกียร์จะมีเสียงดังสุด
* เสียงเร่งและเบรคทำแค่เสียงของเครื่องยนต์ก็พอ

**Comment by ghost** [comment]
สิ่งที่เจมต้องคิดต่อคือจะใช้ค่าหรือฟังชันอะไรในการสร้างความเร็ว
จากที่ได้ศึกษาทดลองฟิสิกส์ ลองคิดดูว่าตัวไหนเหมาะสมที่สุด
ให้ศึกษาวิธีตัวนั้นให้เข้าใจ ว่ามีอะไรเกี่ยวข้องบ้าง
แล้วมาอธิบายใน issue นี้ว่าจะใช้ตัวไหนเพราะอะไร ใช้อย่างไร

**Comment by NattapasJenphet** [comment]
ใช้ตัวแปร speed เป็นตัวกำหนดเกียร์ต่างๆ 
`Car.GetComponent<Rigidbody>().velocity = Vector3.forward * speed; `
ฟังก์ชั่น speedControl()
```
            if (speed <= 20) // 0 - 20
            {
                gear 1
            }
            else if (speed >= 20 && speed <= 52) // 20 - 52
            {
                gear 2 
            }
            else if (speed >= 52 && speed <= 57) // 52 - 57
            {
                gear 3
            }
            else if (speed >= 57) // 57+
            {
                gear 4
            }
```
หรืออาจจะสร้างตัวแปรที่เป็น array มาเก็บค่า gear ต่างๆ เพื่อง่ายต่อการปรับค่า

**Comment by ghost** [comment]
โคดอันนี้เจมใช้ทำไปแล้ว วิธีแบบนี้เป็นการ hardcode ทำให้การปรับแต่งในภายหลังเป็นเรื่องยาก
แน่นอนการโคดเกมเราจะต้องมีการ hardcode เพื่อความรวดเร็ว
แต่ตรงนี้เราต้องทำให้การเคลื่อนที่เป็นไปอย่างสมจริง ควรต้องคิดสมาการ หรือ คำนวน ให้ได้ค่าที่ระเอียดขึ้น

ตอนนี้เจมจะใช้ velocity ในการควบคุมความเร็วให้เจมช่วยแปรภาษาอังกฤษหัวข้อ Description ใน 2 page นี้ให้หน่อยครับ
https://docs.unity3d.com/ScriptReference/Rigidbody.html
https://docs.unity3d.com/ScriptReference/Rigidbody-velocity.html

แล้วสรุปว่าจะใช้ velocity อย่างไรบ้าง
และลองคิดการคำนวนความเร็วตามที่ผมออกแบบไว้อีกครั้งนึ่ง

**Comment by NattapasJenphet** [comment]
ปรับโค้ดด้วยการเพิ่มความเร็วของรถด้วยฟังก์ชั่น wheelCollider.motorTorque 
ตอนนี้ push แล้วช่วยดูหน่อยครับ ว่าสามารถนำไปใช้งานได้รึเปล่า

**Comment by ghost** [comment]
* งานที่ให้ทำเสร็จรึยังครับ
* กดเร่งแล้วไม่เกิดอะไรขึ้นครับ

**Comment by NattapasJenphet** [comment]
ปรับโค้ดเพื่อให้ได้ผลลัพธ์ตามที่ีต้องการ
> การเคลื่อนที่เป็นไปอย่างสมจริง ควรต้องคิดสมาการ หรือ คำนวน ให้ได้ค่าที่ละเอียดขึ้น

กดเร่งด้วยลูกศร Up และ Down ตอนนี้ในฟังก์ชั่นปุ่มยังไม่ได้แก้ไข
งานแปลอยู่ใน wiki ครับ

**Comment by ghost** [comment]
ได้ผลดีมากครับ การวิ่งให้ความรู้สึกไม่กระตุกเลย

**Comment by ghost** [comment]
* commit issue ผิดเบอร์
* เล่นไม่ได้ กดปุ่มไหนก็ไม่มีการเคลื่อนไหว

**Comment by ghost** [comment]
> * เสียงเครื่องยนต์ตามการเร่งและเบรค
> * มีการเปลียนเกียร์ โดยให้กำหนดจำนวนเกียร์ได้ 4-6 เกียร์
> * ปรับปรุงการเร่งให้สามารถกำหนด top speed ได้เป็น km/hr
> * กำหนดเวลาความเร็วจาก 0 - top speed ได้เป็นวินาที

อธิบายแต่ละข้อครับว่าทำอะไรบ้าง ตรงตาม issue ไหม

**Comment by NattapasJenphet** [comment]
> เสียงเครื่องยนต์ตามการเร่งและเบรค

สร้าง method carEngineSound() เพื่อควบคุมค่า pitch ของเสียงเครื่องยนต์ โดยที่ค่า pitch จะเพิ่มขึ้นเรื่อยๆตามการเร่งความเร็วของรถ

> มีการเปลี่ยนเกียร์ โดยให้กำหนดจำนวนเกียร์ได้ 4-6 เกียร์

กำหนดเกียร์เป็น 4 เกียร์ แบ่งตามช่วงความเร็ว (50,100,150,200) มีแต่ละเกียร์มีผลต่อการเพิ่มความเร็วในฟังก์ชั่น motorTorque

> ปรับปรุงการเร่งให้สามารถกำหนด top speed ได้เป็น km/hr

มีตัวแปร engine Torque ที่สามารถกำหนดความเร็ว Top speed ได้ แต่คาด Top speed ที่จะได้ออกมาค่ายังไม่ตายตัว เช่น ค่า engine Torque = 200 ค่า Top speed = 220 km/hr

> กำหนดเวลาความเร็วจาก 0 - top speed ได้เป็นวินาที

สามารถกำหนดเวลาได้ใน method moveCar() กำหนดเวลาได้ในฟังก์ชั่น motorTorque (ซึ่งในตอนนี้ยังไม่สามารถกำหนดได้ )

**Comment by ghost** [comment]
> กำหนดเกียร์เป็น 4 เกียร์ แบ่งตามช่วงความเร็ว (50,100,150,200) มีแต่ละเกียร์มีผลต่อการเพิ่มความเร็วในฟังก์ชั่น motorTorque

ต้องสามารถกำหนดจำนวนเกียร์ได้ว่าจะเป็น 4, 5 หรือ 6 อาจจะมี array 3 ชุดก็ได้

> มีตัวแปร engine Torque ที่สามารถกำหนดความเร็ว Top speed ได้ แต่คาด Top speed ที่จะได้ออกมาค่ายังไม่ตายตัว เช่น ค่า engine Torque = 200 ค่า Top speed = 220 km/hr

หาทางกำหนดให้ได้ อาจจะไม่ตรงแต่ต้องกำหนดให้เห็นความแตกต่างของ top speed

> สามารถกำหนดเวลาได้ใน method moveCar() กำหนดเวลาได้ในฟังก์ชั่น motorTorque (ซึ่งในตอนนี้ยังไม่สามารถกำหนดได้ )

ทำให้ครบครับ อาจใช้วิธีอื่นแทนเวลากำหนดความแตกต่าง

การส่ง review จะต้องทำตามที่ issue เขียนไว้ให้ครบ และสามารถทดสอบได้

ให้เขียนวิธีการทดสอบ
* เปลียนจำนวนเกียร์
* เปลียน top speed
* เปลียนเวลาความเร็วจาก 0 - top

**Comment by NattapasJenphet** [comment]
> เปลียนจำนวนเกียร์

วิธีทดสอบ ตอนนี้สร้าง array 3 ชุดขึ้นมา แบ่งออกเป็น 4, 5, 6 เกียร์

> เปลี่ยน top speed

วิธีทดสอบ เปลี่ยนค่า motorTorque ซึ่งจะเป็นค่าที่กำหนด topspeed ได้ความเร็วที่ได้จะมีค่าใกล้เคียง

> เปลียนเวลาความเร็วจาก 0 - top

วิธีทดสอบ เปลี่ยนค่าตัวแปร m_time ที่สร้างมาช่วยควบคุมการเร่ง ยิ่งค่า m_time มากก็ยิ่งทำให้การเร่งไปยัง top speed นั้นไปได้ช้า
