### ISSUE TITLE
ศึกษา Unity3d เพิ่มเติ่ม

### ISSUE THREAD

**Issue by ghost** [NattapasJenphet/Kiragames_Intern#9]
ให้ศึกษาและทดสอบใช้ โดยสร้าง scene ใหม่ เพื่อแสดงการใช้งาน แล้วมาอธิบายใน issue นี้

* ฟังชัน Update ต่างๆที่มีใน Unity3d
* Physics
    * Velocity
    * AddRelativeForce
    * AddRelativeTorque

**Comment by NattapasJenphet** [comment]
Function update ใน unity 
- **Awake()** 
> Awake จะถูกเรียกใช้งานเมื่อสคริปนั้นถูกโหลดใช้งาน สามารถ Run ได้ถึงแม้ว่า Script ไม่ทำงานก็ตาม
- **Start()**
> Start ฟังก์ชั่นจะถูกเรียกใช้งานบนเฟรมก่อนที่ Update จะถูกเรียกใช้งานเป็นครั้งแรก
- **Update()** 
> ฟังก์ชั่นจะถูกเรียกใช้งานทุกๆเฟรม 
- **FixedUpdate()**
> FixedUpdate ฟังก์ชั่นจะทำงานทุกๆเฟรมตามค่าคงที่
- **LateUpdate()**
> LateUpdate เป็นฟังก์ชั่นที่มีความสามารถเหมือน Update ทุกอย่าง แต่แตกต่างกันที่ LateUpdate ลำดับการทำงานจะช้ากว่าและถูกใช้งานหลังจาก Update ถูกเรียกใช้งานแล้ว

**Comment by NattapasJenphet** [comment]
Physics
- **Velocity** 
> เวกเตอร์ความเร็วของ rigibody ในขณะนั้น
- **AddRelativeForce**
> เป็นก์ชั่นเพิ่มแรงให้กับ rigibody โดยอ้างอิงกับตำแหน่งของ coordinate system. (แกน x y z ของตัว object) ซึ่งแตกต่างจาก addForce ที่เพิ่มแรงไปในทิศทางเดียว
- **AddRelativeTorque**
> เป็นก์ชั่นเพิ่มแรงบิดให้กับ rigibody โดยอ้างอิงกับตำแหน่งของ coordinate system. (แกน x y z ของตัว object)

**Comment by ghost** [comment]
> ให้ศึกษาและทดสอบใช้ โดยสร้าง scene ใหม่ เพื่อแสดงการใช้งาน แล้วมาอธิบายใน issue นี้

อธิบายด้วยครับว่าทำอะไรไปบ้าง ใน scene ทดสอบอะไร ทดสอบแล้วได้อะไรบ้าง

**Comment by NattapasJenphet** [comment]
**ทดสอบการทำงานของฟังก์ชั่น update ต่างๆ**
- ทดสอบ function Awake เมื่อทำการ Disable script
จะเห็นได้ว่ามีเพียงแค่ฟังก์ชั่น Awake ที่สามารถรันได้
![image](https://user-images.githubusercontent.com/33273784/33106433-9de0155e-cf64-11e7-9672-f2584d71f428.png)

- ทดสอบการทำงานของแต่ละฟังก์ชั่นโดยเห็นแสดงเวลา time.deltaTime
ทุกๆฟังก์ชั่นเริ่มทำงานโดยที่มี ฟังก์ชั่น Awake ฟังก์ชั่น Start ฟังก์ชั่น FixedUpdate ฟังก์ชั่น Update ฟังก์ชั่น LastUpdate ตามลำดับที่เวลา 0.02
จะเห็นได้ว่า 
           - ฟังก์ชั่น Awake และ  ฟังก์ชั่น Start จะทำงานเพียงครั้งเดียว
           - ฟังก์ชั่น FixedUpdate จะทำงานทุกๆที่เวลา 0.02 
           - ฟังก์ชั่น Update จะทำงานทุกๆเฟรม
           - ฟังก์ชั่น LastUpdate จะทำงานหลักจากฟังก์ชั่น Update เสมอ
![image](https://user-images.githubusercontent.com/33273784/33106784-91781c60-cf66-11e7-9db6-0dd4de8ee706.png)

**Comment by ghost** [comment]
เรื่อง update ศึกษาว่าการเรียกมันลำดับอย่างไรที่นี้ได้ครับ
https://docs.unity3d.com/Manual/ExecutionOrder.html

**Comment by NattapasJenphet** [comment]
**ทดสอบการทำงานของ Physics ( Velocity ,AddRelativeForce, AddRelativeTorque )**
- ทดสอบค่า velocity ของ object 
โดยที่ add ค่า velocity ไปที่ rigibody `rb.velocity = new Vector3(0, 10f, 0);` 
แปลงค่า Vector ของเป็นค่า float `velocity = rb.velocity.magnitude;`
![up](https://user-images.githubusercontent.com/33273784/33107897-f51dc7b0-cf6b-11e7-8c23-a91c8336452d.png)
เมื่อวัตถุถูกแรงส่งขึ้นไปจะมีค่า velocity เป็นบวก และก่อนที่วัตถุจะตกลงมาค่า velocity เข้าใกล้เลข 0 
![-5da](https://user-images.githubusercontent.com/33273784/33107900-f8b901e6-cf6b-11e7-9abf-43a1046f1c40.png)
 และเมื่อวัตถุตกลงมาค่า velocity จะติดลบ

**Comment by NattapasJenphet** [comment]
- ทดสอบการใช้ AddRelatveForce
 `GetComponent<Rigidbody>().AddRelativeForce(Vector3.forward * 100f);`
![image](https://user-images.githubusercontent.com/33273784/33108369-56fc201a-cf6e-11e7-8bca-5542e50a8274.png)
AddRelativeForce ให้แรงพลักวัตถุ (0 , 0 , 1 ) * 100f ในแกน z 
![image](https://user-images.githubusercontent.com/33273784/33108270-fe1f4792-cf6d-11e7-995e-e3f633137367.png)
เมื่อพลักวัตถุจนล้มทำให้แกน Z ของวัตถุเปลี่ยน ทำให้ไม่สามารถพลักต่อได้ 
แตกต่างจาก AddForce ที่ยังสามารถพลังไปในแกน Z ต่อได้แม้แกนของวัตถุจะเปลี่ยน

- ทดสอบการใช้ AddRelativeTorque
หลักการทำงานเหมือน AddReletiveForce คือทำงานตามแกนของวัตถุ
AddRelativeTorque คือการเพิ่มแรงบิดหมุดของแกน โดยที่ถ้าแรงเป็นค่าบวกจะหมุนไปตามเข็มนาฬิกา 
และตรงกันข้ามถ้าแรงเป็นค่าลบจะหมุุนทวนเข็มนาฬิกา
![image](https://user-images.githubusercontent.com/33273784/33108805-afc9991e-cf70-11e7-8296-0684b652edde.png)
`GetComponent<Rigidbody>().AddRelativeTorque(Vector3.up * 100f);`
เพิ่มแรงไป ( 0 , 1 , 0 ) * 100f ใช้แกน Y เป็นจุดหมุน 
![image](https://user-images.githubusercontent.com/33273784/33108830-d0072dc2-cf70-11e7-89f5-fd20db0a483a.png)
`GetComponent<Rigidbody>().AddRelativeTorque(Vector3.down * 100f);`
